# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcc2be3b063b1bacc1624c73127821b4a6c6cd52cb78c497c002f23ae8f9491db5dcc7cc043cb226c4bbccf4aeee3d1a099db03e36e635f30ab72e450a309a87

test:
  secret_key_base: 3d12c189c8b4d957fe98364e1848a94e98679353455d0501f60edceee721d974b8192a765bafcdc9378a4470815b8cc7d5145c8f12858b7b9a089afaad17e9a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
